version: '3.3'
services:
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        networks:
            - ic_network
        environment:
            - 'PGADMIN_DEFAULT_EMAIL=odoo@eazytraining.fr'
            - 'PGADMIN_DEFAULT_PASSWORD=odoo_pgadmin_password'
        ports:
            - "${PGADMIN_PORT}:80"
        volumes:
            - ${PWD}/servers.json:/pgadmin4/servers.json
            - 'pgadmin_data:/var/lib/pgadmin'
    postgres:
        environment:
            - POSTGRES_USER=odoo_user
            - POSTGRES_PASSWORD=odoo_password
            - POSTGRES_DB=postgres
        networks:
            - ic_network
        volumes:
            - 'pgdata:/var/lib/postgresql/data'
        container_name: postgres
        image: 'postgres:10'
        ports:
            - '5432:5432'
    odoo:
        depends_on:
            - postgres
        ports:
            - '${ODOO_PORT}:8069'
        container_name: odoo
        networks:
            - ic_network
        volumes:
            - 'odoo-web-data:/var/lib/odoo'
        environment:
            - USER=odoo_user
            - PASSWORD=odoo_password
            - HOST=postgres
        image: odoo:13.0

    ic-webapp:
        container_name: ic-webapp
        ports:
            - "${IC_PORT}:8080"
        environment:
            - "ODOO_URL=http://${HOST_IP}:${ODOO_PORT}/"
            - "PGADMIN_URL=http://${HOST_IP}:${PGADMIN_PORT}/"
        image: '${USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}'
        networks:
            - ic_network

volumes:
    odoo-web-data:
    pgdata:
    pgadmin_data:
networks:
    ic_network:
      driver: bridge
      name: ic_network